### ISSUE TITLE
Create initial donor form with submission endpoint

### ISSUE THREAD

**Issue by Guferos** [InkubatorTechnologiczny/shelter#14]
- [ ] Create web form for donor registration
- [ ] Create new view for the form
- [ ] Create endpoint to submit donor
- [ ] Save submission in the db

**Comment by wenta** [comment]
@Guferos 
Regarding the view and endpoint, this task is part of the milestone "Complete structure for the website frontend." so they should just be mocked, right?

**Comment by Guferos** [comment]
@wenta yes. Don't worry about CSS or UI in general atm. We just need to add the bare form, functionality and make submissions saving in the db. We will work on the UI later.
