### ISSUE TITLE
Add database migration files for option tables' inserts

### ISSUE THREAD

**Issue by Guferos** [InkubatorTechnologiczny/shelter#4]
Add 3 database migration files that do inserts for the following tables:

```
Sizes: 
1 Mały
2 Średni
3 Duży

Genders:
1 Samiec
2 Samica

Species:
1 Pies
2 Kot
```

- When doing inserts in the migration file please use `DB` class rather then using models
- Please make sure you also insert timestamps for `updated_at` and `created_at` as these will not populate automatically as we don't use Eloquent models

**Comment by Guferos** [comment]
@WaldemarGoszka 
This is an example showing how to create a migration Class that populates `Sizes` table with options above. I hope it helps:

Firstly, in the terminal, in your project root type:
```
php artisan make:migration seed_sizes_table
```
This will create a new migration class that sits in: \app\database\migrations

Now edit the class and insert options in the `up()` methods then truncate in the `down()` method:

```
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Carbon\Carbon;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        DB::table('sizes')->insert([
            [
                'id' => 1,
                'name' => 'Mały',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now()
            ],
            [
                'id' => 2,
                'name' => 'Średni',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now()
            ],
            [
                'id' => 3,
                'name' => 'Duży',
                'updated_at' => Carbon::now(),
                'created_at' => Carbon::now()
            ]
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        DB::table('sizes')->whereIn('id', [1,2,3])->delete();
    }
};

```
All done!

You can test if tables populate properly by running the following command (`fresh` option will drop all the tables):
```
php artisan migrate:fresh
```

**Comment by WaldemarGoszka** [comment]
Thanks for the tip. Don't you think it's better to add inserts in seeders instead of migration files?

**Comment by Guferos** [comment]
Just for the sake of completion I am going to add here my response from Slack.

We decided to put these inserts into the migration files rather than seeders as these are fixed options that are required to be in the database for the system to work (these will populate in production too). Therefore it makes more sense to keep them here when the database is created. I don't expect these values to ever change and they are also mapped to PHP enums for convienience in the code. We are going to use Seeders and Factories to seed temporary test data only.
