### ISSUE TITLE
Add seeder and factory for AnimalImage

### ISSUE THREAD

**Issue by Guferos** [InkubatorTechnologiczny/shelter#6]
Not sure what we will be the best way to handle that. Need some research and all ideas are welcomed. Maybe we can just add a single image to the project repo and then reference the same image when seeding the table? That could work possibly

**Comment by Guferos** [comment]
@WaldemarGoszka From what I can see you can actually use faker to create fake images. They don't look great as it's a some colour background with a random text, but it would be ok for now. In the future we could implement pulling a random image from a service that provides placeholder images.

**Comment by WaldemarGoszka** [comment]
I'm testing this solution and it's really slow. Generating 50 fake photos takes about 1-2 minute. To be good enough, each animal should have 2-6 photos, which increases the amount of time. I don't know if this will be a good solution for now. In which directory should these fake photos be located? I think in public/storage/animal_fake_photos/ (it's already included in .gitignore)

**Comment by Guferos** [comment]
I don't think we can use it then if it's that slow. Mainly because tests would take too much time and we have limited number of CI minutes on the free Github tier. Maybe we can just put add two images to the storage folder (one with cat and one with dog) and reference the same image for every dog and cat. I don't care if these will be same images as long as it displays and works, as we only need this for testing. Re folder: I am not entirely sure, I think it needs to go to a different directory and then you create a symlink to the public one, have a read here: https://laravel.com/docs/10.x/filesystem
